language: csharp
mono: none
dotnet: 2.2.104
script:
 - dotnet test
 - dotnet build -c Release
 - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push **/NUnitGenerativeTesting.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$