global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
 - dotnet test
 - dotnet build -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack -c Release -p:PackageVersion=$TRAVIS_TAG
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
  provider: script
  script: dotnet nuget push **/NUnitGenerativeTesting.*.nupkg --api-key $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$