language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
 - dotnet test
 - dotnet build -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: 
   - dotnet pack -c Release -p:PackageVersion=$TRAVIS_TAG
   - dotnet nuget push **/NUnitGenerativeTesting.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1